# ./Taskfile.yaml
# See: https://taskfile.dev/api/

version: "3"

tasks:

  migrate:  ## Команда для миграции

    desc: "Migrate database"
    cmds:  ## Тут описываем необходимые bash-команды
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations

  test_migration:
    desc: "Test migrations"
    cmds:
      - go run ./cmd/migrator/main.go --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test
